/*
 * lpm_downward.h
 *
 *  Created on: 2019Äê1ÔÂ10ÈÕ
 *      Author: ASUS
 */

#ifndef EXAMPLES_PLATFORM_SPECIFIC_CC26X0_CC13X0_VERY_SLEEPY_DEMO_LPM_DOWNWARD_LPM_DOWNWARD_H_
#define EXAMPLES_PLATFORM_SPECIFIC_CC26X0_CC13X0_VERY_SLEEPY_DEMO_LPM_DOWNWARD_LPM_DOWNWARD_H_


extern uint8_t is_waiting_downward();
PROCESS_NAME(downward_request_process);

#endif /* EXAMPLES_PLATFORM_SPECIFIC_CC26X0_CC13X0_VERY_SLEEPY_DEMO_LPM_DOWNWARD_LPM_DOWNWARD_H_ */
